CREATE TRIGGER `upd_lignes` BEFORE UPDATE ON `lignes_frais`
 FOR EACH ROW BEGIN

    IF(NEW.DATEFRAIS IS NULL)
	THEN
	INSERT INTO lignes_frais(IDFRAIS, DATEFRAIS) VALUES(IDFRAIS,OLD.DATEFRAIS);
    END IF;
    IF (NEW.KM IS NULL) 
    THEN
        INSERT INTO lignes_frais (IDFRAIS, KM) VALUES (IDFRAIS, OLD.KM);  
     END IF;
    IF (NEW.TRAJET IS NULL) 
    THEN
        INSERT INTO lignes_frais (IDFRAIS, TRAJET) VALUES (IDFRAIS, OLD.TRAJET);  
        END IF;
    IF (NEW.DATEFRAIS IS NULL) 
    THEN
        INSERT INTO lignes_frais (IDFRAIS, DATEFRAIS) VALUES (IDFRAIS, OLD.DATEFRAIS);  
    END IF; 
    END